---
title: "Processed Data"
output: pdf_document
---
```{r, echo = FALSE}
library(dataRetrieval)
library(tidyverse)
library(dygraphs)
library(lubridate)
library(xts)
library(ggplot2)
```

##Pulling and Preliminary Wrangling
```{r, echo = FALSE}
#BLUE SPRINGS
BLUENO3 <- readNWISuv( 
  site = "02319950", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

BLUEdischarge <- readNWISuv( 
  site = "02319950", 
  parameterCd = "00060",
  startDate = "2015-08-11", 
  endDate = "2018-10-30"
) %>% 
  renameNWISColumns

BLUEdata <- full_join(BLUENO3, BLUEdischarge, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

BOWNO3 <- readNWISuv( 
  site = "02313098", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

BOWdischarge <- readNWISuv( 
  site = "02313098", 
  parameterCd = "00060",
  startDate = "2015-10-08", 
  endDate = "2019-06-20"
) %>% 
  renameNWISColumns

BOWdata <- full_join(BOWdischarge, BOWNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#CALOOSAHATCHEE RIVER
CALNO3 <- readNWISuv( 
  site = "02292900", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

CALdischarge <- readNWISuv( 
  site = "02292900", 
  parameterCd = "00060",
  startDate = "2014-12-23", 
  endDate = "2018-10-11"
) %>% 
  renameNWISColumns

CALdata <- full_join(CALdischarge, CALNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#CHASSAHOWITZAKA RIVER
CHASNO3 <- readNWISuv( 
  site = "02310650", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

CHASdischarge <- readNWISuv( 
  site = "02310650", 
  parameterCd = "00060",
  startDate = "2015-09-28", 
  endDate = "2019-06-07"
) %>% 
  renameNWISColumns

CHASdata <- full_join(CHASdischarge, CHASNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#CRANE CREEK
CRANENO3 <- readNWISuv( 
  site = "02249500", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

CRANEdischarge  <- readNWISuv( 
  site = "02249500", 
  parameterCd = "00060",
  startDate = "2014-12-18", 
  endDate = "2016-09-13"
) %>% 
  renameNWISColumns

CRANEdata <- full_join(CRANEdischarge, CRANENO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#DRAINAGE CANAL AT PLAZ PKWY
DRAINNO3 <- readNWISuv( 
  site = "02248600", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

DRAINdischarge <- readNWISuv( 
  site = "02248600", 
  parameterCd = "00060",
  startDate = "2014-07-31", 
  endDate = "2016-10-01"
) %>% 
  renameNWISColumns

DRAINdata <- full_join(DRAINdischarge, DRAINNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#FANNING SPRING
FANNO3 <- readNWISuv( 
  site = "02323502", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

FANdischarge <- readNWISuv( 
  site = "02323502", 
  parameterCd = "00060",
  startDate = "2014-07-03", 
  endDate = "2018-11-15"
) %>% 
  renameNWISColumns

FANdata <- full_join(FANNO3, FANdischarge, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#FELLSMERE CANAL
FELLNO3 <- readNWISuv( 
  site = "02251767", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

FELLdischarge <- readNWISuv( 
  site = "02251767", 
  parameterCd = "00060",
  startDate = "2015-05-27", 
  endDate = "2016-10-19"
) %>% 
  renameNWISColumns

FELLdata <-full_join(FELLdischarge, FELLNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#BLUE HOLE SPRING
HOLNO3 <- readNWISuv( 
  site = "02322688", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

HOLdischarge <- readNWISuv( 
  site = "02322688", 
  parameterCd = "00060",
  startDate = "2014-07-02", 
  endDate = "2019-08-21"
) %>% 
  renameNWISColumns

HOLdata <- full_join(HOLdischarge, HOLNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#HOMOSASSA SPRINGS
HOMNO3 <- readNWISuv( 
  site = "02310678", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

HOMdischarge <- readNWISuv( 
  site = "02310678", 
  parameterCd = "00060",
  startDate = "2015-09-28", 
  endDate = "2018-10-02"
) %>% 
  renameNWISColumns

HOMdata <- full_join(HOMdischarge, HOMNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#HUNTER SPRING RUN
HUNNO3 <- readNWISuv( 
  site = "02310743", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

HUNdischarge <- readNWISuv( 
  site = "02310743", 
  parameterCd = "00060",
  startDate = "2017-01-26", 
  endDate = "2018-10-16"
) %>% 
  renameNWISColumns

HUNdata <- full_join(HUNdischarge, HUNNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#ICHETUCKNEE RIVER
ICHENO3 <- readNWISuv( 
  site = "02322700", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

ICHEdischarge <- readNWISuv( 
  site = "02322700", 
  parameterCd = "00060",
  startDate = "2016-11-15", 
  endDate = "2019-08-19"
) %>% 
  renameNWISColumns

ICHEdata <- full_join(ICHEdischarge, ICHENO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#MADISON BLUE SPRING
MADNO3 <- readNWISuv( 
  site = "02319302", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

MADdischarge <- readNWISuv( 
  site = "02319302", 
  parameterCd = "00060",
  startDate = "2014-07-09", 
  endDate = "2016-11-01"
) %>% 
  renameNWISColumns

MADdata <- full_join(MADdischarge, MADNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#MAIN CANAL AT VERO BEACH
MAINNO3 <- readNWISuv( 
  site = "02253000", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

MAINdischarge <- readNWISuv( 
  site = "02253000", 
  parameterCd = "00060",
  startDate = "2014-09-16", 
  endDate = "2016-10-01"
) %>% 
  renameNWISColumns

MAINdata <- full_join(MAINdischarge, MAINNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#MANATEE SPRINGS
MANNO3 <- readNWISuv( 
  site = "02323566", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

MANdischarge <- readNWISuv( 
  site = "02323566", 
  parameterCd = "00060",
  startDate = "2014-07-09", 
  endDate = "2016-11-01"
) %>% 
  renameNWISColumns

MANdata <- full_join(MANNO3, MANdischarge, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")


#RAINBOW RIVER
RAINNO3 <- readNWISuv( 
  site = "02313100", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

RAINdischarge <- readNWISuv( 
  site = "02313100", 
  parameterCd = "00060",
  startDate = "2015-10-05", 
  endDate = "2019-06-20"
) %>% 
  renameNWISColumns

RAINdata <- full_join(RAINdischarge, RAINNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#SANTA FE RIVER
SANTANO3 <- readNWISuv( 
  site = "02322800", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

SANTAdischarge <- readNWISuv( 
  site = "02322800", 
  parameterCd = "00060",
  startDate = "2012-09-27", 
  endDate = "2016-10-01"
) %>% 
  renameNWISColumns

SANTAdata <- full_join(SANTAdischarge, SANTANO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#THREE MILE CANAL
THREENO3 <- readNWISuv( 
  site = "02289035", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

THREEdischarge <- readNWISuv( 
  site = "02289035", 
  parameterCd = "00060",
  startDate = "2013-10-01", 
  endDate = "2019-04-24"
) %>% 
  renameNWISColumns

THREEdata <- full_join(THREEdischarge, THREENO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#TURKEY CREEK
TURKNO3 <- readNWISuv( 
  site = "02250030", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

TURKdischarge <- readNWISuv( 
  site = "02250030", 
  parameterCd = "00060",
  startDate = "2014-05-30", 
  endDate = "2016-08-10"
) %>% 
  renameNWISColumns

TURKdata <- full_join(TURKdischarge, TURKNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#TURNBULL CREEK
TURNNO3 <- readNWISuv( 
  site = "02248350", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

TURNdischarge <- readNWISuv( 
  site = "02248350", 
  parameterCd = "00060",
  startDate = "2015-11-25", 
  endDate = "2016-09-16"
) %>% 
  renameNWISColumns

TURNdata <- full_join(TURNdischarge, TURNNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")

#WACISSA RIVER
WACNO3 <- readNWISuv( 
  site = "02326526", 
  parameterCd = "99133",
  startDate = "", 
  endDate = ""
) %>% 
  renameNWISColumns %>%
  rename(Nitrate_mgl = 4)

WACdischarge <- readNWISuv( 
  site = "02326526", 
  parameterCd = "00060",
  startDate = "2016-02-17", 
  endDate = "2019-04-11"
) %>% 
  renameNWISColumns

WACdata <- full_join(WACdischarge, WACNO3, by = "dateTime") %>%
  drop_na() %>%
  filter(X_99133_Inst_cd == "A" & Flow_Inst_cd == "A")
```

##In Depth Wrangling
```{r, echo = FALSE}
#BLUEdata
BLUEdata$dateTime <- ymd_hms(BLUEdata$dateTime) 

BLUEdata <- BLUEdata %>% filter(dateTime < "2015-12-30 11:15:00")


#Bow
BOWdata$dateTime <- ymd_hms(BOWdata$dateTime)

BOWdata <- BOWdata %>% filter(dateTime > "2018-01-05 03:30:00" & dateTime < "2018-08-31 12:15:00")


#CALdata
CALdata$dateTime <- ymd_hms(CALdata$dateTime)

CALdata <- CALdata %>% filter(dateTime > "2015-10-31")


#CHASdata
CHASdata$dateTime <- ymd_hms(CHASdata$dateTime)

CHASdata <- CHASdata %>% filter(dateTime > "2018-03-13")


#CRANEdata
CRANEdata$dateTime <- ymd_hms(CRANEdata$dateTime)

CRANEdata <- CRANEdata %>% filter(dateTime < "2015-04-15")


#DRAINdata
DRAINdata$dateTime <- ymd_hms(DRAINdata$dateTime)

DRAINdata <- DRAINdata %>% filter(dateTime > "2015-11-17")


#FANdata
FANdata$dateTime <- ymd_hms(FANdata$dateTime)

FANdata <- FANdata %>% filter(dateTime > "2017-10-27 09:00:00" & dateTime < "2018-05-10 09:45:00")


#FELLdata
FELLdata$dateTime <- ymd_hms(FELLdata$dateTime)

FELLdata <- FELLdata %>% filter(dateTime < "2015-09-24 11:45:00")


#HOLdata
HOLdata$dateTime <- ymd_hms(HOLdata$dateTime)

HOLdata <- HOLdata %>% filter(dateTime > "2016-06-24 12:00:00" & dateTime <"2018-12-16 03:15:00")


#HOMdata
HOMdata$dateTime <- ymd_hms(HOMdata$dateTime)

HOMdata <- HOMdata %>% filter(dateTime > "2017-10-12 12:15:00")


#HUNdata
HUNdata$dateTime <- ymd_hms(HUNdata$dateTime)

HUNdata <- HUNdata %>% filter(dateTime < "2018-08-16 03:30:00")


#ICHEdata
ICHEdata$dateTime <- ymd_hms(ICHEdata$dateTime)

ICHEdata <- ICHEdata %>% filter(dateTime > "2017-09-28 09:15:00" & dateTime < "2018-03-14 10:15:00")


#MADdata
MADdata$dateTime <- ymd_hms(MADdata$dateTime)

MADdata <- MADdata %>% filter(dateTime > "2015-05-11 12:00:00" & dateTime < "2015-12-30 12:15:00")


#MAINdata
MAINdata$dateTime <- ymd_hms(MAINdata$dateTime)

MAINdata <- MAINdata %>% filter(dateTime > "2014-10-10 12:00:00" & dateTime < "2015-06-03 11:45:00")


#MANdata
MANdata$dateTime <- ymd_hms(MANdata$dateTime)

MANdata <- MANdata %>% filter(dateTime > "2016-01-06 03:15:00" & dateTime < "2016-08-30")


#RAINdata
RAINdata$dateTime <- ymd_hms(RAINdata$dateTime)

RAINdata <- RAINdata %>% filter(dateTime > "2016-06-16 04:00:00")


#SANTAdata
SANTAdata$dateTime <- ymd_hms(SANTAdata$dateTime)

SANTAdata <- SANTAdata %>% filter(dateTime > "2013-07-24 12:00:00" & dateTime < "2014-07-24 11:45:00")


#THREEdata
THREEdata$dateTime <- ymd_hms(THREEdata$dateTime)

THREEdata <- THREEdata %>% filter(dateTime > "2016-01-14 01:15:00" & dateTime < "2017-07-25 12:30:00")


#TURKdata
TURKdata$dateTime <- ymd_hms(TURKdata$dateTime)

TURKdata <- TURKdata %>% filter(dateTime > "2014-12-02 12:00:00" & dateTime < "2015-07-02 11:45:00")


#TURNdata
TURNdata$dateTime <- ymd_hms(TURNdata$dateTime)

TURNdata <- TURNdata %>% filter(dateTime > "2015-12-21 10:00:00" & dateTime < "2016-01-24 11:45:00")


#WACdata
WACdata$dateTime <- ymd_hms(WACdata$dateTime)

WACdata <- WACdata %>% filter(dateTime > "2017-12-04 02:45:00" & dateTime < "2018-12-15 05:15:00")
```

##Chemostaticity (C-Q Plots and Regressions)
```{r, echo = FALSE}
#Blue
BLUENitrateDV <- BLUEdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

BLUEFlowDV <- BLUEdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

BLUEChemo <- full_join(BLUENitrateDV, BLUEFlowDV, by = "dateTime")

BLUEChemoplot <- ggplot(BLUEChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Blue Springs Near Dell, FL")
  
print(BLUEChemoplot)

BLUEChemo.lm <- lm(data = BLUEChemo, Flow_DV ~ Nitrate_DV)
summary(BLUEChemo.lm)

#BOW
BOWNitrateDV <- BOWdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

BOWFlowDV <- BOWdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

BOWChemo <- full_join(BOWNitrateDV, BOWFlowDV, by = "dateTime")

BOWChemoplot <- ggplot(BOWChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Rainbow River Near Dunnellon, FL")

print(BOWChemoplot)

BOWChemo.lm <- lm(data = BOWChemo, Flow_DV ~ Nitrate_DV)
summary(BOWChemo.lm)


#CAL
CALNitrateDV <- CALdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

CALFlowDV <- CALdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

CALChemo <- full_join(CALNitrateDV, CALFlowDV, by = "dateTime")

CALChemoplot <- ggplot(CALChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Caloosahatchee River at S-79 Near Olga, FL")

print(CALChemoplot)

CALChemo.lm <- lm(data = CALChemo, Flow_DV ~ Nitrate_DV)
summary(CALChemo.lm)


#CHAS
CHASNitrateDV <- CHASdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

CHASFlowDV <- CHASdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

CHASChemo <- full_join(CHASNitrateDV, CHASFlowDV, by = "dateTime")

CHASChemoplot <- ggplot(CHASChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Chassahowitzka River Near Homosassa, FL")

print(CHASChemoplot)

CHASChemo.lm <- lm(data = CHASChemo, Flow_DV ~ Nitrate_DV)
summary(CHASChemo.lm)


#CRANE
CRANENitrateDV <- CRANEdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

CRANEFlowDV <- CRANEdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

CRANEChemo <- full_join(CRANENitrateDV, CRANEFlowDV, by = "dateTime")

CRANEChemoplot <- ggplot(CRANEChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Crane Creek at Melbourne, FL")

print(CRANEChemoplot)

CRANEChemo.lm <- lm(data = CRANEChemo, Flow_DV ~ Nitrate_DV)
summary(CRANEChemo.lm)


#DRAIN
DRAINNitrateDV <- DRAINdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

DRAINFlowDV <- DRAINdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

DRAINChemo <- full_join(DRAINNitrateDV, DRAINFlowDV, by = "dateTime")

DRAINChemoplot <- ggplot(DRAINChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Drainage Canal at Plaza Pkwy at Cocoa, FL")
  
print(DRAINChemoplot)

DRAINChemo.lm <- lm(data = DRAINChemo, Flow_DV ~ Nitrate_DV)
summary(DRAINChemo.lm)


#FAN
FANNitrateDV <- FANdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

FANFlowDV <- FANdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

FANChemo <- full_join(FANNitrateDV, FANFlowDV, by = "dateTime")

FANChemoplot <- ggplot(FANChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Fanning Springs Near Wilcox, FL")

print(FANChemoplot)

FANChemo.lm <- lm(data = FANChemo, Flow_DV ~ Nitrate_DV)
summary(FANChemo.lm)


#FELL
FELLNitrateDV <- FELLdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

FELLFlowDV <- FELLdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

FELLChemo <- full_join(FELLNitrateDV, FELLFlowDV, by = "dateTime")

FELLChemoplot <- ggplot(FELLChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Fellsmere Canal Near Micco, FL")

print(FELLChemoplot)

FELLChemo.lm <- lm(data = FELLChemo, Flow_DV ~ Nitrate_DV)
summary(FELLChemo.lm)


#HOL
HOLNitrateDV <- HOLdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

HOLFlowDV <- HOLdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

HOLChemo <- full_join(HOLNitrateDV, HOLFlowDV, by = "dateTime")

HOLChemoplot <- ggplot(HOLChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Blue Hole Spring Near Hildreth, FL")

print(HOLChemoplot)

HOLChemo.lm <- lm(data = HOLChemo, Flow_DV ~ Nitrate_DV)
summary(HOLChemo.lm)


#HOM
HOMNitrateDV <- HOMdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

HOMFlowDV <- HOMdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

HOMChemo <- full_join(HOMNitrateDV, HOMFlowDV, by = "dateTime")

HOMChemoplot <- ggplot(HOMChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Homosassa Springs at Homosassa Springs, FL")

print(HOMChemoplot)

HOMChemo.lm <- lm(data = HOMChemo, Flow_DV ~ Nitrate_DV)
summary(HOMChemo.lm)


#HUN
HUNNitrateDV <- HUNdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

HUNFlowDV <- HUNdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

HUNChemo <- full_join(HUNNitrateDV, HUNFlowDV, by = "dateTime")

HUNChemoplot <- ggplot(HUNChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Hunter Spring Run at Beach L at Crystal River, FL")

print(HUNChemoplot)

HUNChemo.lm <- lm(data = HUNChemo, Flow_DV ~ Nitrate_DV)
summary(HUNChemo.lm)


#ICHE
ICHENitrateDV <- ICHEdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

ICHEFlowDV <- ICHEdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

ICHEChemo <- full_join(ICHENitrateDV, ICHEFlowDV, by = "dateTime")

ICHEChemoplot <- ggplot(ICHEChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Ichetucknee River at Hwy27 Near Hildreth, FL")

print(ICHEChemoplot)

ICHEChemo.lm <- lm(data = ICHEChemo, Flow_DV ~ Nitrate_DV)
summary(ICHEChemo.lm)


#MAD
MADNitrateDV <- MADdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

MADFlowDV <- MADdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

MADChemo <- full_join(MADNitrateDV, MADFlowDV, by = "dateTime")

MADChemoplot <- ggplot(MADChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Madison Blue Spring near Blue Springs, FL")

print(MADChemoplot)

MADChemo.lm <- lm(data = MADChemo, Flow_DV ~ Nitrate_DV)
summary(MADChemo.lm)


#MAIN
MAINNitrateDV <- MAINdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

MAINFlowDV <- MAINdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

MAINChemo <- full_join(MAINNitrateDV, MAINFlowDV, by = "dateTime")

MAINChemoplot <- ggplot(MAINChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Main Canal at Vero Beach, FL")

print(MAINChemoplot)

MAINChemo.lm <- lm(data = MAINChemo, Flow_DV ~ Nitrate_DV)
summary(MAINChemo.lm)


#MAN
MANNitrateDV <- MANdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

MANFlowDV <- MANdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

MANChemo <- full_join(MANNitrateDV, MANFlowDV, by = "dateTime")

MANChemoplot <- ggplot(MANChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Manatee Spring Near Chiefland, FL")

print(MANChemoplot)

MANChemo.lm <- lm(data = MANChemo, Flow_DV ~ Nitrate_DV)
summary(MANChemo.lm)

#RAIN
RAINNitrateDV <- RAINdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

RAINFlowDV <- RAINdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

RAINChemo <- full_join(RAINNitrateDV, RAINFlowDV, by = "dateTime")

RAINChemoplot <- ggplot(RAINChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Rainbow River at Dunnellon, FL")

print(RAINChemoplot)

RAINChemo.lm <- lm(data = RAINChemo, Flow_DV ~ Nitrate_DV)
summary(RAINChemo.lm)


#SANTA
SANTANitrateDV <- SANTAdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

SANTAFlowDV <- SANTAdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

SANTAChemo <- full_join(SANTANitrateDV, SANTAFlowDV, by = "dateTime")

SANTAChemoplot <- ggplot(SANTAChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Santa Fe River Near Hildreth, FL")

print(SANTAChemoplot)

SANTAChemo.lm <- lm(data = SANTAChemo, Flow_DV ~ Nitrate_DV)
summary(SANTAChemo.lm)


#THREE
THREENitrateDV <- THREEdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

THREEFlowDV <- THREEdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

THREEChemo <- full_join(THREENitrateDV, THREEFlowDV, by = "dateTime")

THREEChemoplot <- ggplot(THREEChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Three Mile Canal Near Clewiston, FL")

print(THREEChemoplot)

THREEChemo.lm <- lm(data = THREEChemo, Flow_DV ~ Nitrate_DV)
summary(THREEChemo.lm)


#TURK
TURKNitrateDV <- TURKdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

TURKFlowDV <- TURKdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

TURKChemo <- full_join(TURKNitrateDV, TURKFlowDV, by = "dateTime")

TURKChemoplot <- ggplot(TURKChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Turkey Creek at Palm Bay, FL")

print(TURKChemoplot)

TURKChemo.lm <- lm(data = TURKChemo, Flow_DV ~ Nitrate_DV)
summary(TURKChemo.lm)


#TURN
TURNNitrateDV <- TURNdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

TURNFlowDV <- TURNdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

TURNChemo <- full_join(TURNNitrateDV, TURNFlowDV, by = "dateTime")

TURNChemoplot <- ggplot(TURNChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Turnbull Creek Near Oak Hill, FL")

print(TURNChemoplot)

TURNChemo.lm <- lm(data = TURNChemo, Flow_DV ~ Nitrate_DV)
summary(TURNChemo.lm)


#WAC
WACNitrateDV <- WACdata %>%
  group_by(dateTime) %>%
  summarise(Nitrate_DV = mean(Nitrate_mgl))

WACFlowDV <- WACdata %>%
  group_by(dateTime) %>%
  summarise(Flow_DV = mean(Flow_Inst))

WACChemo <- full_join(WACNitrateDV, WACFlowDV, by = "dateTime")

WACChemoplot <- ggplot(WACChemo, aes(x = Flow_DV, y = Nitrate_DV)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Daily Mean Discharge (m/s)", y = "Daily Mean Nitrate (mg/l)") +
  ggtitle("Chemostaticity of Wacissa River Near Wacissa, FL")

print(WACChemoplot)

WACChemo.lm <- lm(data = WACChemo, Flow_DV ~ Nitrate_DV)
summary(WACChemo.lm)

```

##Dygraphs and Hysteresis Loops (Only Hyp2/3 Sites)
```{r, echo = FALSE}
#BLUE
BLUEdata$dateTime <- ymd_hms(BLUEdata$dateTime)

BLUEstorm <- BLUEdata %>%
  filter(dateTime > "2015-08-28 01:00:00" & dateTime < "2015-11-05  04:30:00")

BLUEplot <- ggplot(BLUEstorm, aes(x = Flow_Inst, y = Nitrate_mgl, color = dateTime)) +
  geom_point() +
  labs(x = "Instantaneous Discharge (m/s)", y = "Nitrate Concentration (mg/l)", color = "Date") +
  ggtitle("2015 Storm Event at Blue Springs")
print(BLUEplot)


#CAL
CALdata$dateTime <- ymd_hms(CALdata$dateTime)

CALstorm <- CALdata %>%
  filter(dateTime > "2016-01-27 04:30:00" & dateTime < "2016-02-08 03:15:00")

CALplot <- ggplot(CALstorm, aes(x = Flow_Inst, y = Nitrate_mgl, color = dateTime)) +
  geom_point() +
  labs(x = "Instantaneous Discharge (m/s)", y = "Nitrate Concentration (mg/l)", color = "Date") +
  ggtitle("2016 Storm Event at Caloosahatchee River")
print(CALplot)


#FAN
FANdata$dateTime <- ymd_hms(FANdata$dateTime)

FANstorm <- FANdata %>%
  filter(dateTime > "2017-12-09 07:15:00" & dateTime < "2017-12-12 01:45:00")

FANplot <- ggplot(FANstorm, aes(x = Flow_Inst, y = Nitrate_mgl, color = dateTime)) +
  geom_point() +
  labs(x = "Instantaneous Discharge (m/s)", y = "Nitrate Concentration (mg/l)", color = "Date") +
  ggtitle("2017 Storm Event at Fanning Springs")
print(FANplot)


#MAD
MADdata <- read.csv("/ENV322_group_project/FL_CSV/hyp1/MADdata1.csv")

MADdata$dateTime <- ymd_hms(MADdata$dateTime)

MADstorm <- MADdata %>%
  filter(dateTime > "2015-05-30 04:00:00" & dateTime < "2016-06-05 12:15:00")

MADplot <- ggplot(MADstorm, aes(x = Flow_Inst, y = Nitrate_mgl, color = dateTime)) +
  geom_point() +
  labs(x = "Instantaneous Discharge (m/s)", y = "Nitrate Concentration (mg/l)", color = "Date") +
  ggtitle("2015 Storm Event at Madison Blue Spring") +
  scale_fill_viridis_c(option = "magma")
print(MADplot)
```