---
title: "RBI_CHEMO_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

# read in data from RBI_CHEMO_analysis doc
RBI_CHEMO_data<-read_csv(
  "/Users/ethanready/ENV322_group_project/Processed_Dataframes/RBI_CHEMO_data.csv")
RBI_nocanals<-read_csv(
  "/Users/ethanready/ENV322_group_project/Processed_Dataframes/RBI_CHEMO_nocanals.csv")  


#visualize data, both abs and non-abs
RBI.linear<-ggplot(RBI_CHEMO_data, 
                   aes(x=RBI_value_ind_noncatch, y=chemo.coef))+
  geom_point(aes(color=site.type))+
  labs(x="Richards-Baker Index", y="Chemostaticity Coeffiecient")


RBI.linear.abs<-ggplot(RBI_CHEMO_data, 
                       aes(x=RBI_value_ind_noncatch, y=chemo.coef.abs))+
  geom_point(aes(color=site.type))+
  labs(x="Richards-Baker Index", 
       y="Chemostaticity Coeffiecient Absolute Value")

# run regressions on data
lm_sig<-lm(chemo.coef~RBI_value_ind_noncatch, RBI_CHEMO_data)

lm_sig_abs<-lm(chemo.coef.abs~RBI_value_ind_noncatch, RBI_CHEMO_data)

lm_sig_log_abs<-lm(log(chemo.coef.abs)~RBI_value_ind_noncatch, RBI_CHEMO_data)

summary(lm_sig)
summary(lm_sig_abs)
summary(lm_sig_log_abs)

#log graphs

RBI.log<-ggplot(RBI_CHEMO_data, 
                aes(x=RBI_value_ind_noncatch, y=chemo.coef))+
  geom_point(aes(color=site.type))+
  scale_x_log10()+
  geom_smooth(method="lm", se=FALSE)+
  labs(x="Richards-Baker Index", y="Chemostaticity Coeffiecient")

RBI.log.abs<-ggplot(RBI_CHEMO_data, 
                    aes(x=RBI_value_ind_noncatch, y=chemo.coef.abs))+
  geom_point(aes(color=site.type))+
  scale_x_log10()+
  scale_y_log10()+
  geom_smooth(method="lm", se=FALSE)+
  labs(x="Richards-Baker Index", 
       y="Absulute Value Chemostaticity Coeffiecient")

#same analysis, without canals in the data

Nocanals.linear<-ggplot(RBI_nocanals, 
                        aes(x=RBI_value_ind_noncatch, y=chemo.coef))+
  geom_point(aes(color=site.type))+
  labs(x="Richards-Baker Index", y="Chemostaticity Coeffiecient")


Nocanals.linear.abs<-ggplot(RBI_nocanals, 
                            aes(x=RBI_value_ind_noncatch, y=chemo.coef.abs))+
  geom_point(aes(color=site.type))+
  labs(x="Richards-Baker Index",
       y="Absolute Value Chemostaticity Coeffiecient")

lm_nocanals<-lm(chemo.coef~RBI_value_ind_noncatch, RBI_nocanals)

lm_nocanals_abs<-lm(chemo.coef.abs~RBI_value_ind_noncatch, RBI_nocanals)

lm_nocanals_log_abs<-
  lm(log(chemo.coef.abs)~RBI_value_ind_noncatch, RBI_nocanals)

summary(lm_nocanals)
summary(lm_nocanals_abs)
summary(lm_nocanals_log_abs)
```



